version: '3.8'

# Переопределения для локальной разработки на Windows/Mac.
# Этот файл применяется автоматически при вызове `docker compose up`.
# На продакшн-сервере он не нужен.

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  purchasesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  shopsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  factoriesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
